apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: syfooversikthendelsetilfelle-alerts
  namespace: default
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#syfo-alarm'
      prependText: '<!here> | '
  alerts:
    - alert: SYFOOVERSIKTHENDELSETILFELLE IS DOWN
      expr: up{app="syfooversikthendelsetilfelle", job="kubernetes-pods"} == 0
      for: 5m
      description: "Det er ingen pods for app kjørende i namespace og dermed er appen nede"
      action: "Undersøk hvofor pods er nede og få den kjørende igjen!"
      severity: danger
    - alert: SYFOOVERSIKTHENDELSETILFELLE mislykkes i å sende Oversikthendelsetilfelle for Oppfolgingstilfelle
      expr: sum(increase(syfooversikthendelsetilfelle_oppfolgingstilfelle_skipped_retry_count{app="syfooversikthendelsetilfelle"} [1h])) > 10
      for: 30m
      description: "Minst 1 Oppfolgingstilfelle har ikke produsert Oversikthendelse til topic."
      action: "Minst 1 hendelse har ikke kommet frem dit den skal. Dette må håndteres manuelt slik at Oversikthendelse blir sendt."
      severity: danger
