apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversikthendelsetilfelle
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 100m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfooversikthendelsetilfelle.dev.intern.nav.no"
    - "https://syfooversikthendelsetilfelle.nais.preprod.local"
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/dev/srvsyfooversikthendelsetilfelle"
        mountPath: "/secrets/serviceuser/syfooversikthendelsetilfelle"
  webproxy: true
  env:
    - name: KTOR_ENV
      value: production
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.preprod.local
    - name: AKTORREGISTER_V1_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1
    - name: EREG_API_BASE_URL
      value: https://modapp-q1.adeo.no/ereg/api/
    - name: OPPFOLGINGSTILFELLE_TOPIC
      value: aapen-syfo-oppfolgingstilfelle-v1
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: https://syfobehandlendeenhet.nais.preprod.local
    - name: SYFOSYKETILFELLE_URL
      value: https://syfosyketilfelle.nais.preprod.local
