apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversikthendelsetilfelle
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfooversikthendelsetilfelle.intern.nav.no"
    - "https://syfooversikthendelsetilfelle.nais.adeo.no"
  azure:
    application:
      enabled: true
      tenant: nav.no
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/prod/srvsyfooversikthendelsetilfelle"
        mountPath: "/secrets/serviceuser/syfooversikthendelsetilfelle"
  webproxy: true
  env:
    - name: KTOR_ENV
      value: production
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.adeo.no
    - name: AKTORREGISTER_V1_URL
      value: https://app.adeo.no/aktoerregister/api/v1
    - name: OPPFOLGINGSTILFELLE_TOPIC
      value: aapen-syfo-oppfolgingstilfelle-v1
    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: SYFOSYKETILFELLE_URL
      value: https://syfosyketilfelle.nais.adeo.no
